### ISSUE TITLE
glob pattern doesn't match filenames without dot in the name

### ISSUE THREAD

**Issue by multi** [outbounder/angelscripts-stack-use#1]
look here

> https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/use.js#L98

maybe a better approach will be `glob.create(templatesRoot+"/**/*", {nodir: true, ignore: ["/.git", "/upgrade.json"]})`

**Comment by outbounder** [comment]
@multi well that glob should include directories (opposite of `nodir: true`) because it is doing a copy (+ optional, transformation) of entire directories recursively preserving their structure at the destination (in the case of stack use - `cwd`)

let me know if I've misunderstood something or there is more to be added on this topic or just close ;)

**Comment by multi** [comment]
@outbounder

`nodir: true` - Do not match directories, only files. (Note: to match only directories, simply put a / at the end of the pattern.)
meaning that, there will be no directory paths in the glob. without this flag, here https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/use.js#L68-L69 i get an error, because it's trying to read a directory... so in order to copy empty directories from `upgrade` it will be needed only one `.gitkeep` in them, and voilà :) the next line https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/use.js#L70 will create the needed directory tree ;) (see https://github.com/jprichardson/node-fs-extra#ensurefilefile-callback)

hope this gives more light on the topic :information_desk_person:

**Comment by multi** [comment]
one more, here https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/configure.js#L77, should be changed also to
`glob.create([path.join(process.cwd(), '**/*'), '!node_modules/**', '!build/**', '!upgrades/**', '!.git/**'], {nodir: true})` in order to match files without `.` in the filename

**Comment by outbounder** [comment]
@multi may be there is something else happening so that you got the impression that the globs are the problems?

Can you please post me steps to reproduce the problems + sample test data/folders/structure so that I can see it myself.

But in general, to give you some clues why the globs are such:

> https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/use.js#L98

This glob should iterate all files and folders, it is the copy-paste step. Additionally I've just tested this with empty directory and didn't found any issue with it. Actually the glob is `"/**/*.*"` which will match only files with `.` in their filename, which is a problem because in Unix there could be files without extension ;)

> https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/configure.js#L77

This glob should iterate all files including dot ones, it is a `{{{placeholder}}}` replace and it could happen to have a placeholder in dot file too.

> https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/use.js#L68-L69 i get an error, because it's trying to read a directory

It is really interesting how that happens, can you share more details because I never reached such edge case :)

**Comment by multi** [comment]
@outbounder you can test it from here https://github.com/outbounder/organic-stem-skeleton/pull/8

```
% angel stack use docker-compose
apply upgrade /upgrades/docker/core ...
wrote:  /docker-compose.yml
wrote:  /docker/nginx/stem.nginx.conf
WARNING: docker-compose has peer upgrades but none has been applied. Consider using { 'mongo-sessions': 'mongo-sessions', mongoose: 'mongoose' }
updating package.json stack-upgrades ...
all done, git diff & go
```

as you can see no `Dockerfile` is written

then, change in use.js the glob pattern to `**/*` and run again `% angel stack use docker-compose`
you'll see

```
apply upgrade /upgrades/docker/core ...
failed to read:  /Users/gy/Developer/Camplight/organic-stem-skeleton/upgrades/docker/core/docker
failed to read:  /Users/gy/Developer/Camplight/organic-stem-skeleton/upgrades/docker/core/docker/nginx
failed to read:  /Users/gy/Developer/Camplight/organic-stem-skeleton/upgrades/docker/core/docker/nodejs
wrote:  /docker-compose.yml
wrote:  /docker/nginx/stem.nginx.conf
wrote:  /docker/nodejs/Dockerfile
wrote:  /docker/nginx/Dockerfile
```

then change `dot:true` to `{nodir: true}` and run again

```
apply upgrade /upgrades/docker/core ...
wrote:  /docker/nodejs/Dockerfile
wrote:  /docker/nginx/Dockerfile
wrote:  /docker/nginx/stem.nginx.conf
wrote:  /docker-compose.yml
WARNING: docker-compose has peer upgrades but none has been applied. Consider using { 'mongo-sessions': 'mongo-sessions', mongoose: 'mongoose' }
updating package.json stack-upgrades ...
all done, git diff & go
```

**Comment by outbounder** [comment]
@multi got it.

Well changing https://github.com/outbounder/angelscripts-stack-use/blob/master/scripts/use.js#L98 which globs all files having `.` in their path to be

`templatesRoot+"/**/*", {dot: true, ignore: ["/.git", "/upgrade.json"]}` will resolve this problem I believe.

Will release a new version after mocking that as test.
